// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHu1RAz4u4_2LDt7WIMa4A6z_RNKGATrE',
    appId: '1:203675335638:web:d51502272288d3bf388277',
    messagingSenderId: '203675335638',
    projectId: 'mediqueue-ab22e',
    authDomain: 'mediqueue-ab22e.firebaseapp.com',
    storageBucket: 'mediqueue-ab22e.firebasestorage.app',
    measurementId: 'G-53Q5GGNDSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDapnC8nhcQJtOQf2OJdsTe7Z6AGSFJWUc',
    appId: '1:203675335638:android:05910e2e1cb119d7388277',
    messagingSenderId: '203675335638',
    projectId: 'mediqueue-ab22e',
    storageBucket: 'mediqueue-ab22e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx94SCxJElkidITbL2_Hzf_wdAGOSnYaE',
    appId: '1:203675335638:ios:3795d250d86a31af388277',
    messagingSenderId: '203675335638',
    projectId: 'mediqueue-ab22e',
    storageBucket: 'mediqueue-ab22e.firebasestorage.app',
    iosBundleId: 'com.example.mediqueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx94SCxJElkidITbL2_Hzf_wdAGOSnYaE',
    appId: '1:203675335638:ios:3795d250d86a31af388277',
    messagingSenderId: '203675335638',
    projectId: 'mediqueue-ab22e',
    storageBucket: 'mediqueue-ab22e.firebasestorage.app',
    iosBundleId: 'com.example.mediqueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHu1RAz4u4_2LDt7WIMa4A6z_RNKGATrE',
    appId: '1:203675335638:web:627c6ead19bb4cda388277',
    messagingSenderId: '203675335638',
    projectId: 'mediqueue-ab22e',
    authDomain: 'mediqueue-ab22e.firebaseapp.com',
    storageBucket: 'mediqueue-ab22e.firebasestorage.app',
    measurementId: 'G-5ZKPLDE3L7',
  );
}
